export const architectureAnalysisStyles = `
.architecture-analysis-board{border-top:1px solid #e5e0d5;border-bottom:1px solid #e5e0d5;padding:16px 24px;background:#fffdf8}.architecture-analysis-tabs{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.architecture-analysis-tabs button{border:1px solid #ddd7cc;background:#fffdf8;border-radius:9px;padding:9px 14px;font-size:14px;color:#41493c}.architecture-analysis-tabs button[aria-pressed=true]{background:#eee2d7;border-color:#d3a88e;color:#753d29}.architecture-analysis-tabs .analysis-scope{margin-left:auto;font-size:14px;color:#525b4b}.architecture-analysis-content{margin-top:14px;max-height:290px;overflow:auto}.analysis-row{display:flex;gap:12px;align-items:flex-start;padding:11px 0;border-top:1px solid #eee9de}.analysis-row:first-child{border-top:0}.analysis-row-main{flex:1;min-width:0}.analysis-row strong{font-size:14px;color:#31392d}.analysis-row p{font-size:13px;color:#545e4b;margin:5px 0;line-height:1.6}.analysis-row code{font-size:12px;overflow-wrap:anywhere}.analysis-level{font-size:12px;border-radius:6px;padding:4px 7px;background:#e9ece0;color:#46543c}.analysis-level[data-severity=error]{background:#f8ded1;color:#9e422a}.analysis-level[data-severity=warning]{background:#f2e9cc;color:#735816}.analysis-note{font-size:14px;color:#505a48;line-height:1.6;margin:0 0 10px}.analysis-paths{display:flex;gap:7px;flex-wrap:wrap}.analysis-paths button{font-size:13px}.analysis-empty{font-size:14px;color:#535d4c;margin:12px 0}.analysis-status-omit{color:#72695d}.analysis-ci-summary{font-size:16px;font-weight:650;color:#34412e;margin:0 0 10px}.architecture-analysis-toggle{font-size:13px}
`;

export const architectureAnalysisClient = String.raw`
function localizedFindingTitle(finding){
 if(finding.code==='dependency-cycle')return tfmt('{count} 个模块存在循环依赖',{count:finding.nodeIds.length});
 if(finding.code==='forbidden-layer-dependency')return tfmt('{layers} 违反声明的分层规则',{layers:finding.title.replace(/ 违反声明的分层规则$/,'')});
 if(finding.code==='coupling-observation'){const parts=finding.title.match(/^(.*) · 扇入 (\d+) \/ 扇出 (\d+)$/);if(parts)return parts[1]+' · '+tfmt('扇入 {incoming} / 扇出 {outgoing}',{incoming:parts[2],outgoing:parts[3]})}
 return finding.title;
}

const architectureReasonLabels=localizedValues(()=>({'missing-git-baseline':t('没有固定 Git 基线'),'removed-or-renamed-dependencies-require-baseline-graph':t('删除或重命名需要旧版依赖图，保守执行全量'),'changed-input-outside-structure':t('变更包含结构图以外的输入'),'incomplete-static-dependency-graph':t('静态依赖解析存在缺口'),'no-changed-inputs-run-full-to-avoid-empty-pass':t('未发现变更，执行全量以避免空运行通过'),'global-configuration-changed':t('全局配置或依赖锁发生变更'),'no-selected-required-check':t('增量选择没有必需检查，执行全量')}));
const architectureCheckReasons=localizedValues(()=>({'default-full':t('默认全量'),'conservative-fallback':t('信息不足，保守回退'),'always-or-unscoped':t('始终运行或未声明输入范围'),'affected-input':t('匹配变更或消费者输入'),'declared-scope-unaffected':t('声明范围未受影响'),'required-check-dependency':t('选中检查的必需前置项'),'affected-check-dependency':t('前置检查输入发生变化'),'runtime-or-environment-check':t('依赖当前运行环境，始终运行')}));
function architectureAnalysisLinks(box,ids){const links=text('div',undefined,'analysis-paths');for(const id of ids.slice(0,8)){const node=architectureIndex.byId.get(id);if(node)links.append(button(node.path,()=>architectureSelect(id), 'text-button'))}box.append(links)}
function architectureAnalysisBoard(){let board=$('architecture-analysis-board');if(!board){board=text('section',undefined,'architecture-analysis-board');board.id='architecture-analysis-board';board.setAttribute('aria-label',t('架构诊断与 CI 计划'));document.querySelector('.architecture-layout').after(board)}board.replaceChildren();const analysis=architectureData.analysis,impact=architectureData.impact,plan=architectureData.ciPlan;const tabs=text('div',undefined,'architecture-analysis-tabs'),mode=architectureState.analysisTab||'analysis';for(const [id,label,count] of [['analysis',t('架构诊断'),analysis?.findings?.length],['impact',t('变更影响'),impact?.affected?.length],['ci',t('CI 计划'),plan?.selectedCount]]){const control=button(label+(count!==undefined?' · '+count:''),()=>{architectureState.analysisTab=id;architectureState.analysisExpanded=false;architectureSave();architectureAnalysisBoard()});control.dataset.analysisTab=id;control.setAttribute('aria-pressed',String(mode===id));tabs.append(control)}const scope=text('span',impact?.baseline?t('基线 ')+impact.baseline.commit.slice(0,8):t('当前封存结构'),'analysis-scope');tabs.append(scope);board.append(tabs);const content=text('div',undefined,'architecture-analysis-content');content.id='architecture-analysis-content';board.append(content);const limit=architectureState.analysisExpanded?200:6;
if(mode==='analysis'){if(!analysis){content.append(text('p',t('此历史运行尚未采集架构分析；运行新检查后查看。'),'analysis-empty'));return}content.append(text('p',t('只依据已解析的静态导入和包依赖。循环与耦合是风险观察；显式分层规则违规有独立证据。'),'analysis-note'));for(const finding of analysis.findings.slice(0,limit)){const row=text('article',undefined,'analysis-row'),level=text('span',({error:t('规则违规'),warning:t('风险观察'),info:t('耦合观察')})[finding.severity],'analysis-level');level.dataset.severity=finding.severity;const main=text('div',undefined,'analysis-row-main');main.append(text('strong',localizedFindingTitle(finding)),text('p',t(finding.reason)));architectureAnalysisLinks(main,finding.nodeIds);row.append(level,main);content.append(row)}if(!analysis.findings.length)content.append(text('p',t('未发现当前规则可证明的架构问题。'),'analysis-empty'));if(analysis.unresolvedRelations)content.append(text('p',analysis.unresolvedRelations+t(' 条关系尚未解析；未发现不代表全架构无风险。'),'analysis-note'));if(analysis.omittedFindings)content.append(text('p',t('另有 ')+analysis.omittedFindings+t(' 条结果超出保存上限。'),'analysis-note'));if(analysis.findings.length>limit)content.append(button(t('展开其余 ')+(analysis.findings.length-limit)+t(' 条'),()=>{architectureState.analysisExpanded=true;architectureAnalysisBoard()},'text-button'))}
else if(mode==='impact'){if(!impact){content.append(text('p',t('此历史运行尚未采集变更影响。'),'analysis-empty'));return}content.append(text('p',impact.changedPaths.length+t(' 个变更路径 · ')+impact.affected.length+t(' 个潜在受影响节点；沿反向静态依赖和包成员传播，未证明实际故障。'),'analysis-note'));for(const reason of impact.fallbackReasons)content.append(text('p',architectureReasonLabels[reason]||reason,'analysis-note'));for(const item of impact.affected.slice(0,limit)){const row=text('article',undefined,'analysis-row'),main=text('div',undefined,'analysis-row-main');main.append(text('strong',item.path),text('p',item.reason==='changed'?t('直接变更'):item.reason==='package-member'?t('包成员保守扩展'):t('静态依赖消费者')));architectureAnalysisLinks(main,[item.nodeId,...(item.via?[item.via.nodeId]:[])]);row.append(main);content.append(row)}if(!impact.affected.length)content.append(text('p',t('当前没有可定位的变更影响。使用 --base 固定比较基线。'),'analysis-empty'));if(impact.affected.length>limit)content.append(button(t('展开更多影响节点'),()=>{architectureState.analysisExpanded=true;architectureAnalysisBoard()},'text-button'))}
else{if(!plan){content.append(text('p',t('此运行没有项目 CI 选择计划；Agent 用例仍按显式选择执行。'),'analysis-empty'));return}content.append(text('p',t('执行 ')+plan.selectedCount+' / '+plan.checks.length+t(' 项 · ')+plan.omittedCount+t(' 项省略')+(plan.mode==='reduced'?t(' · 增量范围'):t(' · 全量范围')),'analysis-ci-summary'),text('p',t('省略不计为通过。输入范围由项目配置声明；需要全量验收时移除 --affected。'),'analysis-note'));for(const reason of plan.fallbackReasons)content.append(text('p',architectureReasonLabels[reason]||reason,'analysis-note'));for(const item of plan.checks.slice(0,limit)){const row=text('article',undefined,'analysis-row'),main=text('div',undefined,'analysis-row-main');main.append(text('strong',(item.action==='run'?t('执行 · '):t('省略 · '))+item.id),text('p',architectureCheckReasons[item.reason]||item.reason));if(item.matchedPaths.length)main.append(text('code',item.matchedPaths.slice(0,4).join(' · ')));if(item.action==='run'&&current?.checks?.some(check=>check.id===item.id))main.append(button(t('检查结果与证据'),()=>openCheckDrawer(current,item.id),'text-button'));row.append(main);content.append(row)}if(plan.checks.length>limit)content.append(button(t('展开其余检查计划'),()=>{architectureState.analysisExpanded=true;architectureAnalysisBoard()},'text-button'))}}
const architectureAnalysisBaseDraw=architectureDraw;
architectureDraw=function(){architectureAnalysisBaseDraw();if(architectureData&&architectureState)architectureAnalysisBoard()};
const architectureAnalysisBaseDetail=architectureDetail;
architectureDetail=function(){architectureAnalysisBaseDetail();const node=architectureIndex?.byId.get(architectureState?.selected);if(!node)return;const box=$('architecture-detail'),members=architectureMembers(node),findings=(architectureData.analysis?.findings||[]).filter(item=>item.nodeIds.some(id=>members.has(id)));if(findings.length){const section=text('section',undefined,'diagnostic-section');section.append(text('h4',t('架构诊断 · ')+findings.length));for(const finding of findings.slice(0,6)){section.append(text('strong',localizedFindingTitle(finding)),text('p',t(finding.reason)));architectureAnalysisLinks(section,finding.nodeIds)}box.append(section)}const affected=architectureData.impact?.affected?.find(item=>item.nodeId===node.id);if(affected){const section=text('section',undefined,'diagnostic-section');section.append(text('h4',t('变更影响解释')),text('p',t('这是潜在影响，未证明发生故障。')));let item=affected;const chain=[],seen=new Set();while(item&&!seen.has(item.nodeId)&&chain.length<24){seen.add(item.nodeId);chain.push(item.nodeId);item=architectureData.impact.affected.find(value=>value.nodeId===item.via?.nodeId)}architectureAnalysisLinks(section,chain);box.append(section)}};
const architectureAnalysisBaseRestore=architectureRestore;
architectureRestore=function(id,data){architectureAnalysisBaseRestore(id,data);try{const saved=JSON.parse(sessionStorage.getItem(architectureKey(id))||'{}');if(['analysis','impact','ci'].includes(saved.analysisTab))architectureState.analysisTab=saved.analysisTab}catch{}};
const architectureAnalysisBaseRender=render;
render=function(run){architectureAnalysisBaseRender(run);if(run.checkSelection?.mode==='reduced'){$('kind').textContent=t('PROJECT · 增量');$('progress-note').hidden=false;$('progress-note').textContent=t('选中 ')+run.checkSelection.selected+' / '+run.checkSelection.planned+t(' 项 · ')+run.checkSelection.omitted+t(' 项省略，未计为通过');$('pass-note').textContent=t('仅统计本次实际执行的通过项')}};
const architectureAnalysisBaseInvalidate=architectureInvalidate;
architectureInvalidate=function(id){const active=id===architectureRunId;architectureAnalysisBaseInvalidate(id);if(active)$('architecture-analysis-board')?.remove()};
`;
