export const controlScript = String.raw`
'use strict';
const $ = id => document.getElementById(id);
let data, mode, token = '', view = 'overview', selected, pending;
const titles = {overview:['每一次进化，都有据可循。','理解质量变化、追溯版本来源，并做出受保护的决策。'],lineage:['版本之间，证据相连。','基线 → 候选 → 活动记录；实际加载经验独立核对。'],quality:['看见长期变化。','固定锚点观察累计退化；缺失测量不绘制为零。'],approvals:['让决策留下依据。','操作由受信后端执行；批准不会自动运行或部署。'],audit:['每个决定，都可追溯。','持久化请求、版本指纹和结果；未决操作阻断后续写入。']};
const labels = {'audit.reconcile':'确认已人工核对未决效果（不重放）','anchor.create':'建立固定锚点','holdout.rotate':'轮换保留集','holdout.exposure':'登记保留集暴露','soft.approve':'批准经验试验','soft.revoke':'撤销经验批准','soft.rollback':'回滚经验版本','experience.revoke':'撤销经验','hard.approve':'批准源码候选','hard.revoke':'撤销源码候选','hard.rollback':'回滚源码版本','authorization.revoke':'撤销授权','loop.stop':'停止循环','loop.takeover':'人工接管','loop.revoke':'撤销循环授权'};
function el(tag, cls, text) { const n=document.createElement(tag); if(cls)n.className=cls;if(text!==undefined)n.textContent=String(text);return n; }
function pill(v){return el('span','pill '+(['passed','completed','within_threshold','active'].includes(v)?'good':['failed','detected','pending','risk_detected'].includes(v)?'attention':''),v??'不可用');}
function metric(v,suffix=''){return typeof v==='number'&&Number.isFinite(v)?v.toFixed(2)+suffix:'不可用';}
function detail(value,label='查看证据元数据'){const d=el('details');d.append(el('summary','',label),el('pre','mono',JSON.stringify(value,null,2)));return d;}
function card(title,desc){const c=el('section','card'),h=el('div','card-head');h.append(el('h2','',title));if(desc)h.append(el('p','',desc));c.append(h);return c;}
function empty(text){return el('div','empty',text);}
function table(headers,rows){const w=el('div','table-wrap'),t=el('table'),head=el('tr');headers.forEach(h=>head.append(el('th','',h)));const th=el('thead');th.append(head);t.append(th);const b=el('tbody');rows.forEach(row=>{const tr=el('tr');row.forEach(v=>{const td=el('td');td.append(v instanceof Node?v:document.createTextNode(String(v??'不可用')));tr.append(td);});b.append(tr);});t.append(b);w.append(t);return rows.length?w:empty('暂无对应证据。');}
function row(k,v){const r=el('div','row');r.append(el('span','label',k),v instanceof Node?v:el('span','mono',v??'不可用'));return r;}
function overview(root){const stats=el('div','stats');[['已记录运行',data.runs.length,'基于本地持久化结果'],['活动经验',data.activeExperience?.entries?.length??0,'不等于每次运行均已加载'],['固定锚点',data.anchors.length,'累计漂移独立观察'],['待决审计',data.audit.filter(a=>a.status==='pending'&&!a.resolution).length,'未决写入保持失败关闭']].forEach(([k,v,n])=>{const s=el('div','stat');s.append(el('div','stat-label',k),el('div','stat-value',v),el('div','stat-note',n));stats.append(s);});root.append(stats);const grid=el('div','grid'),q=card('最新实际测量','硬门禁与语义评估分开呈现'),r=data.runs[0];if(r){q.append(row('运行',r.runId),row('硬门禁',pill(r.quality.hardGate)),row('实测通过率',metric(r.quality.passRate,'%')),row('真实 Judge 均分',metric(r.quality.judgeScore)),el('p','notice','Agent 输出不计为独立质量证据。缺失 Judge、stub 或不完整运行显示不可用。'));}else q.append(empty('暂无运行，请先使用原有 Canary 评估流程。'));const loop=card('循环控制','观察不会启动后台执行');loop.append(row('状态',pill(data.loop.state)),row('轮次',data.loop.round),row('停止原因',data.loop.stopReason??'未记录'),row('授权',data.loop.authorizationId),detail(data.budget,'预算：费用 / 时间 / 工具 / 轮次'));grid.append(q,loop);root.append(grid);const a=card('授权边界','授权状态按当前时间重新计算');a.append(table(['授权','模式','有效性','到期时间','额度'],data.authorizations.map(a=>[a.id,a.mode,pill(a.live?'live':'unavailable'),a.expiresAt??'未设置',detail(a.budget)])));root.append(a);}
function lineage(root){const runs=card('运行谱系与实际加载','经验指针表示配置状态；loadedExperiences 才是该次运行加载记录。');runs.append(table(['基线','运行 / 候选','状态','实际加载经验','独立准入'],data.runs.map(r=>[r.baselineRunId??'基线／独立运行',r.runId,pill(r.status),r.loadedExperiences.length?detail(r.loadedExperiences,'经验版本与内容哈希'): '未记录加载经验',r.admission?detail(r.admission):'不可用'])));root.append(runs);for(const [title,items] of [['经验试验',data.trials],['源码候选（自述不参与准入）',data.candidates],['已应用源码记录（非当前磁盘完整性证明）',data.activeVersions],['经验版本',data.experiences]]){const c=card(title);items.forEach(x=>{c.append(row(x.id??x.journalId,pill(x.status??'applied')),detail(x));});if(!items.length)c.append(empty('暂无记录。'));root.append(c);}const p=card('当前经验指针');p.append(detail(data.activeExperience,'活动版本绑定'));root.append(p);}
function chart(points){const ns='http://www.w3.org/2000/svg',s=document.createElementNS(ns,'svg');s.setAttribute('viewBox','0 0 720 180');s.setAttribute('class','chart');s.setAttribute('role','img');s.setAttribute('aria-label','相对固定锚点的通过率变化；缺失值断线，不按零绘制');const valid=points.filter(p=>p.passDelta!==null);if(!valid.length)return empty('暂无可比测量，不绘制零值曲线。');const span=Math.max(2,...valid.map(p=>Math.abs(p.passDelta)));const line=document.createElementNS(ns,'path');line.setAttribute('d','M 24 90 L 696 90');line.setAttribute('stroke','currentColor');line.setAttribute('opacity','.25');s.append(line);let d='',connect=false;points.forEach((p,i)=>{if(p.passDelta===null){connect=false;return;}const x=24+i*672/Math.max(1,points.length-1),y=90-p.passDelta/span*66;d+=(connect?' L ':' M ')+x+' '+y;connect=true;const dot=document.createElementNS(ns,'circle');dot.setAttribute('cx',x);dot.setAttribute('cy',y);dot.setAttribute('r','4');dot.setAttribute('fill','currentColor');const title=document.createElementNS(ns,'title');title.textContent=p.runId+': '+metric(p.passDelta,' pp');dot.append(title);s.append(dot);});const path=document.createElementNS(ns,'path');path.setAttribute('d',d);path.setAttribute('fill','none');path.setAttribute('stroke','currentColor');path.setAttribute('stroke-width','