import { controlStyles } from "./control-styles.js";
import { controlScript } from "./control-client.js";
export { controlStyles, controlScript };
export function renderControlPage(): string {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark light"><title>Canary · Quality control</title><link rel="stylesheet" href="/control.css"><script src="/control.js" defer></script></head><body>
<a class="skip" href="#main">跳转到主内容</a>
<aside class="sidebar"><a class="brand" href="/" aria-label="Canary home"><span class="brand-icon">c</span>canary<span class="brand-dot">®</span></a><div class="workspace"><span class="eyebrow">LOCAL WORKSPACE</span><strong id="projectName">正在连接项目</strong><span class="local"><i></i> 本地证据 · 无云端依赖</span></div><nav aria-label="Control navigation"><button class="nav active" data-view="overview"><span>◈</span>总览 Overview</button><button class="nav" data-view="experiences"><span>✧</span>项目经验 Experience</button><button class="nav" data-view="lineage"><span>⑂</span>版本谱系 Lineage</button><button class="nav" data-view="quality"><span>⌁</span>质量观察 Quality</button><button class="nav" data-view="approvals"><span>◇</span>操作与审批 Actions<b id="actionCount">0</b></button><button class="nav" data-view="audit"><span>≡</span>审计记录 Audit</button></nav><div class="side-bottom"><span class="eyebrow">TRUST BY DESIGN</span><p>测量不是自述。<br>批准不是自动发布。</p><button id="theme" class="text-button">◐ 切换明暗主题</button><div class="version">L-02 / CONTROL PLANE</div></div></aside>
<div class="shell"><header class="topbar"><div class="breadcrumb">Workspace <span>/</span> <strong id="breadcrumb">Overview</strong></div><div class="top-actions"><button id="mobileTheme" class="button mobile-only" aria-label="切换明暗主题">◐</button><span id="access" class="pill">只读访问</span><button id="refresh" class="button ghost">↻ 刷新</button><button id="unlock" class="button">解锁操作权限</button></div></header>
<main id="main" tabindex="-1"><div class="heading"><div><div class="eyebrow accent">OBSERVE. VERIFY. DECIDE.</div><h1 id="pageTitle">每一次进化，都有据可循<span>.</span></h1><p id="pageDescription">理解质量变化、追溯版本来源，并做出受保护的决策。</p></div><div class="sync"><i></i><span id="syncText">正在读取本地证据</span></div></div><div id="error" class="alert" role="alert" hidden></div><div id="content" aria-live="polite"><div class="empty">正在读取项目证据…</div></div><footer><span>CANARY CONTROL <b>·</b> Local-first, evidence-led.</span><span>UNKNOWN ≠ ZERO</span></footer></main></div>
<dialog id="authDialog"><form id="authForm"><div class="eyebrow accent">OPERATOR ACCESS</div><h2>解锁受保护操作</h2><p>凭证只保存在页面内存中；刷新后需要重新输入。操作者身份由本地凭证持有者声明，不是多用户身份认证。</p><label>操作凭证<input id="token" type="password" autocomplete="off" required minlength="32" placeholder="CANARY_CONTROL_TOKEN"></label><div class="dialog-actions"><button type="button" class="button ghost" data-close="authDialog">取消</button><button class="button primary" type="submit">验证操作权限</button></div><div id="authError" class="alert" role="alert" hidden></div></form></dialog>
<dialog id="actionDialog"><form id="actionForm"><div class="eyebrow accent">VERSION-BOUND DECISION</div><h2 id="actionTitle">确认操作</h2><p id="actionTarget"></p><div class="notice">操作绑定当前证据版本。后端重新校验权限和状态；证据变化将拒绝执行。</div><label>操作者<input name="actor" required maxlength="160" placeholder="姓名或操作身份"></label><label>决策理由<textarea name="reason" required maxlength="1000" rows="3" placeholder="说明本次操作的依据与目的"></textarea></label><label id="thresholdField" hidden>累计退化阈值（百分点）<input name="threshold" type="number" min="0.01" max="100" step="0.01" value="2"></label><div id="exposureFields" hidden><label>暴露渠道<select name="channel"><option value="operator">人工查看</option><option value="proposal">候选生成／提案</option><option value="training">训练／调优</option></select></label><label>证据引用（仅哈希落盘）<input name="reference" maxlength="1000"></label></div><div id="actionError" class="alert" role="alert" hidden></div><div class="dialog-actions"><button type="button" class="button ghost" data-close="actionDialog">取消</button><button id="confirmAction" class="button primary" type="submit">确认并写入审计</button></div></form></dialog><div id="toast" role="status" hidden></div><noscript><p>启用 JavaScript，或使用 canary control status / audit / act 查看与操作。</p></noscript></body></html>`;
}
