export const controlScript = String.raw`
'use strict';
const $ = id => document.getElementById(id);
let data, mode, token = '', view = 'overview', selected, pending;
const titles = {overview:['每一次进化，都有据可循。','理解质量变化、追溯版本来源，并做出受保护的决策。'],experiences:['从问题到经验，逐步验证。','查看候选来源、适用范围、回放收益与受保护的操作。'],lineage:['版本之间，证据相连。','基线 → 候选 → 活动记录；经验送达回报独立核对。'],quality:['看见长期变化。','固定锚点观察累计退化；缺失测量不绘制为零。'],approvals:['让决策留下依据。','操作由受信后端执行；批准不会自动运行或部署。'],audit:['每个决定，都可追溯。','持久化请求、版本指纹和结果；未决操作阻断后续写入。']};
const labels = {'audit.reconcile':'确认已人工核对未决效果（不重放）','anchor.create':'建立固定锚点','holdout.rotate':'轮换保留集','holdout.exposure':'登记保留集暴露','soft.approve':'批准经验试验','soft.revoke':'撤销经验批准','soft.rollback':'回滚经验版本','experience.revoke':'撤销经验','hard.approve':'批准源码候选','hard.revoke':'撤销源码候选','hard.rollback':'回滚源码版本','authorization.revoke':'撤销授权','loop.stop':'停止循环','loop.takeover':'人工接管','loop.revoke':'撤销循环授权'};
function el(tag, cls, text) { const n=document.createElement(tag); if(cls)n.className=cls;if(text!==undefined)n.textContent=String(text);return n; }
function pill(v){return el('span','pill '+(['passed','completed','within_threshold','active'].includes(v)?'good':['failed','detected','pending','risk_detected'].includes(v)?'attention':''),v??'不可用');}
function metric(v,suffix=''){return typeof v==='number'&&Number.isFinite(v)?v.toFixed(2)+suffix:'不可用';}
function detail(value,label='查看证据元数据'){const d=el('details');d.append(el('summary','',label),el('pre','mono',JSON.stringify(value,null,2)));return d;}
function card(title,desc){const c=el('section','card'),h=el('div','card-head');h.append(el('h2','',title));if(desc)h.append(el('p','',desc));c.append(h);return c;}
function empty(text){return el('div','empty',text);}
function table(headers,rows){const w=el('div','table-wrap'),t=el('table'),head=el('tr');headers.forEach(h=>head.append(el('th','',h)));const th=el('thead');th.append(head);t.append(th);const b=el('tbody');rows.forEach(row=>{const tr=el('tr');row.forEach(v=>{const td=el('td');td.append(v instanceof Node?v:document.createTextNode(String(v??'不可用')));tr.append(td);});b.append(tr);});t.append(b);w.append(t);return rows.length?w:empty('暂无对应证据。');}
function row(k,v){const r=el('div','row');r.append(el('span','label',k),v instanceof Node?v:el('span','mono',v??'不可用'));return r;}
function deliveryLabel(status){return {delivered:'经验已送达',partial:'经验未完整送达',selected:'仅选择，尚未送达',unsupported:'适配器不支持经验送达',unknown:'送达状态未知',unrecorded:'未记录选择或送达'}[status]??'送达状态未知';}
function experienceSummary(run){const refs=run.experienceReferences??run.loadedExperiences??[],counts={delivered:0,partial:0,selected:0,unsupported:0,unknown:0};refs.forEach(ref=>{let status=ref.deliveryStatus;if(status==='delivered'&&!(ref.delivery?.status==='delivered'&&ref.delivery.adapter==='function'&&ref.verifiedDelivery?.executionIds?.length))status='unknown';counts[Object.hasOwn(counts,status)?status:'unknown']++;});return {references:refs,counts,text:'已送达 '+counts.delivered+' · 未完整送达 '+counts.partial+' · 仅选择 '+counts.selected+' · 不支持 '+counts.unsupported+' · 未知 '+counts.unknown};}
function overview(root){const stats=el('div','stats');[['已记录运行',data.runs.length,'基于本地持久化结果'],['活动经验',data.activeExperience?.entries?.length??0,'活动指针表示配置状态'],['固定锚点',data.anchors.length,'累计漂移独立观察'],['待决审计',data.audit.filter(a=>a.status==='pending'&&!a.resolution).length,'未决写入保持失败关闭']].forEach(([k,v,n])=>{const s=el('div','stat');s.append(el('div','stat-label',k),el('div','stat-value',v),el('div','stat-note',n));stats.append(s);});root.append(stats);const grid=el('div','grid'),q=card('最新实际测量','硬门禁与语义评估分开呈现'),r=data.runs[0];if(r){q.append(row('运行',r.runId),row('硬门禁',pill(r.quality.hardGate)),row('实测通过率',metric(r.quality.passRate,'%')),row('真实 Judge 均分',metric(r.quality.judgeScore)),el('p','notice','Agent 输出不计为独立质量证据。缺失 Judge、stub 或不完整运行显示不可用。'));}else q.append(empty('暂无运行，请先使用原有 Canary 评估流程。'));const loop=card('循环控制','观察不会启动后台执行');loop.append(row('状态',pill(data.loop.state)),row('轮次',data.loop.round),row('停止原因',data.loop.stopReason??'未记录'),row('授权',data.loop.authorizationId),detail(data.budget,'预算：费用 / 时间 / 工具 / 轮次'));grid.append(q,loop);root.append(grid);const a=card('授权边界','授权状态按当前时间重新计算');a.append(table(['授权','模式','有效性','到期时间','额度'],data.authorizations.map(a=>[a.id,a.mode,pill(a.live?'live':'unavailable'),a.expiresAt??'未设置',detail(a.budget)])));root.append(a);}
function lineage(root){const runs=card('运行谱系与经验送达','执行回报确认经验已传入函数 Agent；使用与收益需独立验证。');runs.append(table(['基线','运行 / 候选','状态','经验送达记录','独立准入'],data.runs.map(r=>{const summary=experienceSummary(r);return [r.baselineRunId??'基线／独立运行',r.runId,pill(r.status),summary.references.length?detail(summary.references,summary.text):'未记录选择或送达',r.admission?detail(r.admission):'不可用'];})));root.append(runs);for(const [title,items] of [['经验试验',data.trials],['源码候选（自述不参与准入）',data.candidates],['已应用源码记录（非当前磁盘完整性证明）',data.activeVersions],['经验版本',data.experiences]]){const c=card(title);items.forEach(x=>{c.append(row(x.id??x.journalId,pill(x.status??'applied')),detail(x));});if(!items.length)c.append(empty('暂无记录。'));root.append(c);}const p=card('当前经验指针');p.append(detail(data.activeExperience,'活动版本绑定'));root.append(p);}
function experienceView(root){
  const stats=el('div','stats');
  [['待验证候选',data.experiences.filter(e=>e.status==='proposed').length,'需完成独立回放'],['已验证',data.experiences.filter(e=>e.status==='validated').length,'使用前核对试验状态'],['正在活动',data.activeExperience?.entries?.length??0,'经验送达以执行回报为准'],['已回滚试验',data.trials.filter(t=>t.status==='rolled_back').length,'旧指针精确恢复']].forEach(([label,value,note])=>{const s=el('div','stat');s.append(el('div','stat-label',label),el('div','stat-value',value),el('div','stat-note',note));stats.append(s);});
  root.append(stats);
  if(!data.experiences.length){root.append(empty('暂无项目经验。失败检查封存后可用 canary experience propose-project 生成候选。'));return;}
  const list=el('div','experience-list');
  data.experiences.forEach(e=>{
    const trial=data.trials.filter(t=>t.experienceId===e.id).at(-1),c=el('article','card experience-card'),head=el('div','experience-head');
    const title=el('div');title.append(el('span','eyebrow accent',e.provenance?'PROJECT EXPERIENCE':'EXPERIENCE'),el('h2','',e.summary??e.key),el('p','mono small',e.id));head.append(title,pill(e.status));c.append(head);
    const facts=el('div','experience-facts');
    facts.append(row('来源运行',e.provenance?.runId??e.source?.ref??'未记录'),row('来源检查',e.provenance?.checkId??'未声明'),row('错误类别',e.provenance?.category??'未分类'),row('适用用例',(e.scope?.caseIds??[]).join(', ')||'未限定'),row('最近选择',e.lastSelectedRunId??'未记录'),row('最近已送达',e.lastDeliveredRunId??'未发现完整送达回报'),row('送达状态',deliveryLabel(e.latestDeliveryStatus)));
    c.append(facts);
    if(trial){const verified=trial.deliveryVerified&&trial.validation?.valid,outcome=el('div','experience-outcome');outcome.append(row('独立回放',pill(trial.status)),row('收益',verified?(trial.comparison?.verdict??'不可用'):'不可用（送达未核对）'),row('改善',verified?((trial.comparison?.improvements??[]).join(', ')||'无'):'不可用'),row('回归',verified?((trial.comparison?.regressions??[]).join(', ')||'无'):'不可用'),row('验证',trial.validation?.valid?(trial.deliveryVerified?'通过':'未知（送达未核对）'):'未通过'));c.append(outcome);}
    else c.append(el('p','notice','尚无独立回放证据；候选不得批准或激活。'));
    c.append(detail({source:e.source,provenance:e.provenance,scope:e.scope,contentHash:e.contentHash,limitations:e.limitations,validation:e.validation,trial:trial??null},'查看来源、适用条件与验证证据'));
    const controls=el('div','experience-controls');
    data.actions.filter(a=>(a.target===e.id&&a.action==='experience.revoke')||(trial&&a.target===trial.id&&['soft.approve','soft.revoke','soft.rollback'].includes(a.action))).forEach(a=>{const b=el('button','button',a.action==='experience.revoke'&&e.status==='proposed'?'拒绝候选':labels[a.action]);b.disabled=!token;b.onclick=()=>openAction(a);controls.append(b);});
    if(controls.childNodes.length)c.append(controls);
    list.append(c);
  });root.append(list);
}
function chart(points){const ns='http://www.w3.org/2000/svg',s=document.createElementNS(ns,'svg');s.setAttribute('viewBox','0 0 720 180');s.setAttribute('class','chart');s.setAttribute('role','img');s.setAttribute('aria-label','相对固定锚点的通过率变化；缺失值断线，不按零绘制');const valid=points.filter(p=>p.passDelta!==null);if(!valid.length)return empty('暂无可比测量，不绘制零值曲线。');const span=Math.max(2,...valid.map(p=>Math.abs(p.passDelta)));const line=document.createElementNS(ns,'path');line.setAttribute('d','M 24 90 L 696 90');line.setAttribute('stroke','currentColor');line.setAttribute('opacity','.25');s.append(line);let d='',connect=false;points.forEach((p,i)=>{if(p.passDelta===null){connect=false;return;}const x=24+i*672/Math.max(1,points.length-1),y=90-p.passDelta/span*66;d+=(connect?' L ':' M ')+x+' '+y;connect=true;const dot=document.createElementNS(ns,'circle');dot.setAttribute('cx',x);dot.setAttribute('cy',y);dot.setAttribute('r','4');dot.setAttribute('fill','currentColor');const title=document.createElementNS(ns,'title');title.textContent=p.runId+': '+metric(p.passDelta,' pp');dot.append(title);s.append(dot);});const path=document.createElementNS(ns,'path');path.setAttribute('d',d);path.setAttribute('fill','none');path.setAttribute('stroke','currentColor');path.setAttribute('stroke-width','2');s.append(path);return s;}
function qualityView(root){if(!data.anchors.length)root.append(empty('尚无固定锚点。请在操作页为完整运行建立锚点。'));data.anchors.forEach(a=>{const c=card('固定锚点 · '+a.runId,'阈值 '+a.threshold+' pp · 原始证据 '+(a.intact?'完整':'缺失或已改变'));c.append(chart(a.points),table(['后续运行','通过率 Δ(pp)','Judge Δ','漂移','可比性'],a.points.map(p=>[p.runId,metric(p.passDelta),metric(p.judgeDelta),pill(p.drift),detail(p.reasons,'原因')])),detail({fingerprint:a.fingerprint,createdAt:a.createdAt}));root.append(c);});const e=card('保留集轮换与泄漏审计','仅展示哈希与计数，不返回保留集输入；未观测到重叠不等于证明无泄漏。');e.append(table(['周期','来源运行','用例数','状态'],data.epochs.map(x=>[x.id,x.runId,x.caseCount,x.retiredAt?'已轮换':'当前'])));data.leakage.forEach(x=>e.append(row(x.epochId,pill(x.status)),detail(x,'重叠与人工暴露记录')));root.append(e);const measured=card('实测指标 / Agent 自述','以下指标只来自执行与评估产物；Agent 自述明确排除。');measured.append(table(['运行','硬门禁','通过率','语义 Judge','Agent 自述'],data.runs.map(r=>[r.runId,pill(r.quality.hardGate),metric(r.quality.passRate,'%'),metric(r.quality.judgeScore),r.agentClaims.status])));root.append(measured);}
function actions(root){const c=card('受保护操作','操作列表是入口，不代表已满足后端全部前置条件。证据变化需重新确认。');if(!token)c.append(el('p','notice',mode==='read_only'?'服务端只读。重启时显式配置凭证才可操作。':'当前只读；输入操作凭证后方可提交。'));const search=el('input');search.type='search';search.placeholder='筛选操作或目标 ID';search.setAttribute('aria-label','筛选操作');const list=el('div','action-list');function draw(){list.replaceChildren();data.actions.filter(a=>(labels[a.action]+' '+a.target).toLowerCase().includes(search.value.toLowerCase())).forEach(a=>{const n=el('div','action-card'),text=el('div');text.append(el('strong','',labels[a.action]??a.action),el('p','mono small',a.target));const b=el('button','button',token?'审阅并确认':'只读');b.disabled=!token;b.onclick=()=>openAction(a);n.append(text,b);list.append(n);});if(!list.childNodes.length)list.append(empty('没有匹配的可操作证据。'));}search.oninput=draw;draw();c.append(search,list);root.append(c);}
function audit(root){const c=card('持久化决策记录','pending 表示可能已有部分效果；禁止盲目重试或删除审计。');const list=el('div','timeline');[...data.audit].reverse().forEach(a=>{const e=el('article','event');e.append(row(labels[a.action]??a.action,pill(a.resolution?'reconciled (原状态 pending)':a.status)),el('p','mono small',a.at+' · '+a.target),el('p','',a.actor+' · '+a.reason),detail(a,'请求 ID / 版本 / 结果'));list.append(e);});c.append(data.audit.length?list:empty('暂无决策。只读查看不会产生写审计。'));root.append(c);}
function render(){if(!data)return;$('content').replaceChildren();$('pageTitle').textContent=titles[view][0];$('pageDescription').textContent=titles[view][1];$('breadcrumb').textContent=view;$('actionCount').textContent=data.actions.length;$('projectName').textContent=data.projectRoot.split(/[\\/]/).pop();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));({overview,experiences:experienceView,lineage,quality:qualityView,approvals:actions,audit}[view])($('content'));}
function error(id,message){$(id).textContent=message;$(id).hidden=!message;}
async function refresh(){try{const r=await fetch('/api/control');const body=await r.json();if(!r.ok)throw Error(body.error);data=body.snapshot;mode=body.mode;$('syncText').textContent='已同步 '+new Date(data.at).toLocaleTimeString();$('unlock').disabled=mode==='read_only';render();error('error','');}catch(e){error('error',e.message);}}
function openAction(a){selected=a;pending=null;$('actionForm').reset();$('actionTitle').textContent=a.action==='experience.revoke'&&data.experiences.find(e=>e.id===a.target)?.status==='proposed'?'拒绝候选':labels[a.action];$('actionTarget').textContent=a.target+' · '+a.revision;$('thresholdField').hidden=a.action!=='anchor.create';$('exposureFields').hidden=a.action!=='holdout.exposure';$('actionForm').elements.namedItem('reference').required=a.action==='holdout.exposure';error('actionError','');$('actionDialog').showModal();}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render();});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('refresh').onclick=refresh;$('theme').onclick=$('mobileTheme').onclick=()=>{document.body.classList.toggle('light');};$('unlock').onclick=()=>{error('authError','');$('authDialog').showModal();};
$('authForm').onsubmit=async e=>{e.preventDefault();try{const candidate=$('token').value;const r=await fetch('/api/control/session',{method:'POST',headers:{'x-canary-control-token':candidate}});if(!r.ok)throw Error((await r.json()).error);token=candidate;$('token').value='';$('access').textContent='操作权限已验证';$('unlock').textContent='重新验证凭证';$('authDialog').close();render();}catch(e){error('authError',e.message);}};
$('actionForm').onsubmit=async e=>{e.preventDefault();const b=$('confirmAction');b.disabled=true;try{const f=new FormData(e.target);if(!pending){pending={action:selected.action,target:selected.target,expectedRevision:selected.revision,requestId:'web_'+crypto.randomUUID(),actor:f.get('actor'),reason:f.get('reason')};if(selected.action==='anchor.create')pending.threshold=Number(f.get('threshold'));if(selected.action==='holdout.exposure'){pending.channel=f.get('channel');pending.reference=f.get('reference');}}const r=await fetch('/api/control/actions',{method:'POST',headers:{'content-type':'application/json','x-canary-control-token':token},body:JSON.stringify(pending)});const body=await r.json();if(!r.ok)throw Error(body.error+'；如需更改请求，请关闭窗口、刷新后重新确认。');$('actionDialog').close();$('toast').textContent='操作完成，审计已保存：'+body.audit.id;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,6000);await refresh();}catch(e){error('actionError',e.message);}finally{b.disabled=false;}};
refresh();
`;
