/** Uses textContent for every project-provided value. No remote assets or third-party scripts. */
export function renderProjectPage(token = ""): string {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Canary · 项目报告</title><style>
*{box-sizing:border-box}body{margin:0;background:#101316;color:#eef0ed;font:15px/1.6 system-ui,"Segoe UI",sans-serif}button,select{font:inherit}button,select,a.download{background:#232b30;color:#eef0ed;border:1px solid #46535a;border-radius:7px;padding:7px 12px;cursor:pointer}button:disabled{opacity:.45;cursor:default}button:hover:enabled,a:hover{border-color:#e8b879}a{color:#e8b879}header{display:flex;justify-content:space-between;gap:16px;padding:24px 32px;border-bottom:1px solid #313b42}header b{font-size:25px;color:#e8b879}small,.muted{color:#a5b3ba}main{display:grid;grid-template-columns:270px minmax(0,1fr);max-width:1500px;margin:auto}aside{padding:24px;border-right:1px solid #313b42}article{padding:28px;min-width:0}h1{font-size:26px;margin:0 0 8px}h2{font-size:19px}#history button{display:block;width:100%;text-align:left;margin-bottom:9px;overflow-wrap:anywhere}#history .selected{border-color:#e8b879;background:#393025}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:24px 0}.metric,.check,.comparison{border:1px solid #39454c;border-radius:10px;background:#181e22;padding:17px}.metric strong{font-size:27px;display:block}.toolbar{display:flex;gap:10px;flex-wrap:wrap;align-items:center}.check{margin:12px 0}.check-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.check h3{margin:0;font-size:17px}.status{font-weight:600}.passed{color:#86d7a0}.failed,.blocked{color:#ffac99}.running{color:#efc78c}.excluded{color:#a5b3ba}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#101316;padding:12px;border-radius:6px;font:13px/1.6 ui-monospace,monospace;max-height:280px;overflow:auto}.notice{background:#242f37;border-left:3px solid #e8b879;padding:12px;margin:14px 0;overflow-wrap:anywhere}#error{border-color:#ffac99;color:#ffac99}#identity{overflow-wrap:anywhere}details summary{cursor:pointer;margin-top:10px}.comparison div{padding:8px;border-bottom:1px solid #39454c}.pill{font-size:12px;border:1px solid #52616b;border-radius:12px;padding:2px 8px}footer{margin-top:26px;color:#a5b3ba}progress{width:100%;accent-color:#e8b879;height:8px}@media(max-width:800px){main{grid-template-columns:1fr}aside{border-right:0;border-bottom:1px solid #313b42}#history{max-height:200px;overflow:auto}.metrics{grid-template-columns:repeat(2,1fr)}header,article{padding:18px}.check-head{flex-wrap:wrap}}
</style></head><body><header><div><b>Canary</b><div class="muted">本地项目报告 · 数据仅来自当前项目</div></div><div class="toolbar"><span id="connection" class="pill">连接中</span><button id="close">停止页面服务</button></div></header><main><aside><h2>运行历史</h2><div id="history">正在读取…</div></aside><article><h1>项目检查</h1><div id="identity" class="muted">等待运行</div><div id="error" class="notice" hidden role="alert"></div><div id="notice" class="notice" hidden></div><div class="metrics"><div class="metric"><strong id="status">—</strong>运行状态</div><div class="metric"><strong id="passed">0</strong>通过</div><div class="metric"><strong id="failed">0</strong>失败 / 阻塞</div><div class="metric"><strong id="progress">0 / 0</strong>已处理检查</div></div><progress id="bar" max="1" value="0"></progress><div class="toolbar"><button id="retry">重跑失败项</button><a id="json" class="download">JSON 报告</a><a id="junit" class="download">JUnit 报告</a><a id="markdown" class="download">Markdown 报告</a></div><div id="active" class="notice" hidden></div><section id="checks"></section><h2>与历史运行比较</h2><div class="toolbar"><select id="baseline" aria-label="基线运行"></select><button id="compare">比较</button></div><div id="comparison"></div><footer>重跑会重新执行选中项及其依赖，生成独立证据。停止页面服务不会取消正在进行的检查。</footer></article></main><script>
const writeToken=${JSON.stringify(token).replaceAll("<", "\\u003c")};
${client}
</script></body></html>`;
}

const client = String.raw`
const $=id=>document.getElementById(id), labels={running:'运行中',completed:'已完成',failed:'失败',cancelled:'已中断',passed:'通过',blocked:'阻塞',excluded:'不适用','not-run':'未运行'};
let selected=new URLSearchParams(location.search).get('runId'), runs=[], stream, stopped=false, current, refreshBusy=false;
const expanded=new Set();
const note=(id,text)=>{$(id).hidden=!text;$(id).textContent=text};
async function api(path,body){const res=await fetch(path,body?{method:'POST',headers:{'content-type':'application/json','x-canary-write-token':writeToken},body:JSON.stringify(body)}:undefined);const value=await res.json();if(!res.ok)throw new Error(value.error||'请求失败');return value}
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node}
const advice={assertion:'核对预期与实际输出，修正被测项目后重跑。',dependency:'先修复未通过的依赖，重跑会重新执行依赖。',environment:'检查执行器、Docker daemon 或目标服务是否可用。',timeout:'检查阻塞原因；确认合理后调整 timeoutMs。',budget:'检查总预算和耗时，再显式重跑。',cancelled:'此次检查已中断，可显式重跑。',configuration:'检查配置、路径和运行环境。',policy:'检查网络授权和路径边界，不要绕过隐私保护。',artifact:'保留现场，检查 artifact 完整性与磁盘权限。',internal:'保留本地证据，使用最小配置复现。'};
function render(run){if(stopped)return;current=run;$('identity').textContent=run.runId+' · '+run.startedAt+(run.retryOf?' · 重跑自 '+run.retryOf:'');$('status').textContent=labels[run.status]||run.status;$('status').className=run.status;$('passed').textContent=run.passedCases;$('failed').textContent=(run.checks||[]).filter(c=>['failed','blocked'].includes(c.status)).length;$('progress').textContent=(run.checks||[]).length+' / '+run.totalCases;$('bar').max=run.totalCases||1;$('bar').value=(run.checks||[]).length;
note('active',run.status==='running'?(run.activeCheck?'正在执行 '+run.activeCheck.id:'正在准备检查与证据'):'');$('retry').disabled=run.status==='running'||!(run.checks||[]).some(c=>['failed','blocked'].includes(c.status));
for(const [id,format] of [['json','json'],['junit','junit'],['markdown','markdown']]){$(id).href='/api/runs/'+encodeURIComponent(run.runId)+'/report/'+format;$(id).setAttribute('download',run.runId+'.'+(format==='junit'?'xml':format==='markdown'?'md':'json'))}
$('checks').replaceChildren();for(const c of run.checks||[]){const card=el('div',undefined,'check'),head=el('div',undefined,'check-head'),title=el('div');title.append(el('h3',c.id),el('small',c.type+' · '+(c.required?'必需':'可选')+' · '+c.durationMs+' ms · '+c.evidence));const status=el('span',labels[c.status]||c.status,'status '+c.status),button=el('button','单项重跑');button.disabled=run.status==='running';button.onclick=()=>retry({checkId:c.id});head.append(title,status,button);card.append(head);if(c.category!=='none'&&c.category!=='platform')card.append(el('p',c.category+' — '+(advice[c.category]||'查看本地报告。')));if(c.observations)card.append(el('p','可用内存 '+c.observations.freeMemoryMb+' MiB · 可用磁盘 '+c.observations.freeDiskMb+' MiB'));const details=el('details'),summary=el('summary','执行信息与脱敏日志');const detailKey=run.runId+':'+c.id;details.open=expanded.has(detailKey);details.ontoggle=()=>{if(details.isConnected){if(details.open)expanded.add(detailKey);else expanded.delete(detailKey)}};details.append(summary,el('pre',c.cwd+(c.command?'\n'+c.command+' '+(c.args||[]).join(' '):'')+(c.httpStatus?'\nHTTP '+c.httpStatus:'')+'\n'+(c.stdout||'')+'\n'+(c.stderr||'')+(c.outputTruncated?'\n[日志为有界摘要]':'')));if(c.childRun)details.append(el('p','子运行证据：'+c.childRun.runId));card.append(details);$('checks').append(card)}}
async function select(id){selected=id;history.replaceState(null,'','?runId='+encodeURIComponent(id));stream?.close();try{render(await api('/api/runs/'+encodeURIComponent(id)));note('error','');stream=new EventSource('/api/runs/'+encodeURIComponent(id)+'/events');for(const name of ['run.snapshot','run.updated','run.finished','run.started'])stream.addEventListener(name,event=>{try{const data=JSON.parse(event.data);if(data.payload?.runId===selected)render(data.payload)}catch{note('error','无法解析运行事件')}});stream.addEventListener('run.error',()=>note('error','运行失败，请查看本地证据。'));stream.onopen=()=>{$('connection').textContent='实时连接'};stream.onerror=()=>{if(!stopped)$('connection').textContent='连接中断，正在重连'};await historyList()}catch(error){if(!stopped)note('error',error.message)}}
async function historyList(){if(stopped||refreshBusy)return;refreshBusy=true;try{runs=(await api('/api/runs')).filter(r=>r.checks);$('history').replaceChildren();const previous=$('baseline').value;$('baseline').replaceChildren();for(const r of runs){const b=el('button',(labels[r.status]||r.status)+' · '+r.passedCases+'/'+r.totalCases+'\n'+r.runId,r.runId===selected?'selected':'');b.onclick=()=>select(r.runId);$('history').append(b);if(r.runId!==selected){const option=el('option',r.runId);option.value=r.runId;$('baseline').append(option)}}if([...$('baseline').options].some(o=>o.value===previous))$('baseline').value=previous;const active=runs.find(r=>r.runId===selected);if(active?.integrity?.status==='invalid'){stream?.close();note('error','证据完整性校验失败，已停止展示运行内容。');$('checks').replaceChildren();$('retry').disabled=true}else if(active&&current?.runId===active.runId)render(active);$('compare').disabled=!$('baseline').options.length;if(!selected&&runs.length)void select(runs[0].runId)}catch(error){if(!stopped)note('error',error.message)}finally{refreshBusy=false}}
async function retry(body){try{const result=await api('/api/runs/'+encodeURIComponent(selected)+'/retry',body);note('error','');await select(result.runId)}catch(error){if(!stopped)note('error',error.message)}}
$('retry').onclick=()=>retry({failed:true});$('compare').onclick=async()=>{try{const value=await api('/api/compare?baseline='+encodeURIComponent($('baseline').value)+'&candidate='+encodeURIComponent(selected));const panel=el('div',undefined,'comparison');for(const c of value.checks||[])panel.append(el('div',c.id+'：'+(labels[c.before]||c.before)+' → '+(labels[c.after]||c.after)));$('comparison').replaceChildren(panel)}catch(error){if(!stopped)note('error',error.message)}};
$('close').onclick=async()=>{try{await api('/api/session/close',{});stopped=true;stream?.close();clearInterval(poll);$('connection').textContent='页面服务已停止';document.querySelectorAll('button,select').forEach(node=>node.disabled=true);note('notice','页面服务已停止。进行中的检查继续运行，结果会保存到本地 artifact。')}catch(error){if(!stopped)note('error',error.message)}};
const poll=setInterval(historyList,2000);if(selected)void select(selected);else void historyList();
`;
